using Volo.Abp.BlobStoring;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekum.Permissions;
using AhlanFeekum.Governorates;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekum.Shared;

namespace AhlanFeekum.Governorates
{
    public class GovernoratesAppService : GovernoratesAppServiceBase, IGovernoratesAppService
    {
        //<suite-custom-code-autogenerated>
        public GovernoratesAppService(IGovernorateRepository governorateRepository, GovernorateManager governorateManager, IDistributedCache<GovernorateDownloadTokenCacheItem, string> downloadTokenCache, IRepository<AppFileDescriptors.AppFileDescriptor, Guid> appFileDescriptorRepository, IBlobContainer<GovernorateFileContainer> blobContainer)
            : base(governorateRepository, governorateManager, downloadTokenCache, appFileDescriptorRepository, blobContainer)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}