using AhlanFeekum.UserProfiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekum.Tickets
{
    public class Ticket : TicketBase
    {
        //<suite-custom-code-autogenerated>
        protected Ticket()
        {

        }

        public Ticket(Guid id, Guid? userProfileId, string firstName, string lastName, string description, bool isFixed)
            : base(id, userProfileId, firstName, lastName, description, isFixed)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}