using AhlanFeekum.Shared;
using AhlanFeekum.SiteProperties;
using AhlanFeekum.UserProfiles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekum.Permissions;
using AhlanFeekum.PropertyEvaluations;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekum.Shared;

namespace AhlanFeekum.PropertyEvaluations
{
    public class PropertyEvaluationsAppService : PropertyEvaluationsAppServiceBase, IPropertyEvaluationsAppService
    {
        //<suite-custom-code-autogenerated>
        public PropertyEvaluationsAppService(IPropertyEvaluationRepository propertyEvaluationRepository, PropertyEvaluationManager propertyEvaluationManager, IDistributedCache<PropertyEvaluationDownloadTokenCacheItem, string> downloadTokenCache, IRepository<AhlanFeekum.UserProfiles.UserProfile, Guid> userProfileRepository, IRepository<AhlanFeekum.SiteProperties.SiteProperty, Guid> sitePropertyRepository)
            : base(propertyEvaluationRepository, propertyEvaluationManager, downloadTokenCache, userProfileRepository, sitePropertyRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}