using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekum.AhlanfeekumTerms
{
    public class AhlanfeekumTermManager : AhlanfeekumTermManagerBase
    {
        //<suite-custom-code-autogenerated>
        public AhlanfeekumTermManager(IAhlanfeekumTermRepository ahlanfeekumTermRepository)
            : base(ahlanfeekumTermRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}