using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekum.AhlanfeekumTerms
{
    public class AhlanfeekumTerm : AhlanfeekumTermBase
    {
        //<suite-custom-code-autogenerated>
        protected AhlanfeekumTerm()
        {

        }

        public AhlanfeekumTerm(Guid id, string termsTitle, string termsAnnotation, string termsDescription, Guid termsIconId, string termsIconExtension, string whoAreWeTitle, string whoAreWeDescription, Guid whoAreWeIconId, string whoAreWeIconExtension, bool isActive, string? whoAreWeAnnotation = null)
            : base(id, termsTitle, termsAnnotation, termsDescription, termsIconId, termsIconExtension, whoAreWeTitle, whoAreWeDescription, whoAreWeIconId, whoAreWeIconExtension, isActive, whoAreWeAnnotation)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}