using AhlanFeekum.Shared;
using AhlanFeekum.Reservations;
using AhlanFeekum.UserProfiles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekum.Permissions;
using AhlanFeekum.CashPayments;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekum.Shared;

namespace AhlanFeekum.CashPayments
{
    public class CashPaymentsAppService : CashPaymentsAppServiceBase, ICashPaymentsAppService
    {
        //<suite-custom-code-autogenerated>
        public CashPaymentsAppService(ICashPaymentRepository cashPaymentRepository, CashPaymentManager cashPaymentManager, IDistributedCache<CashPaymentDownloadTokenCacheItem, string> downloadTokenCache, IRepository<AhlanFeekum.UserProfiles.UserProfile, Guid> userProfileRepository, IRepository<AhlanFeekum.Reservations.Reservation, Guid> reservationRepository)
            : base(cashPaymentRepository, cashPaymentManager, downloadTokenCache, userProfileRepository, reservationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}