using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekum.Governorates
{
    public class Governorate : GovernorateBase
    {
        //<suite-custom-code-autogenerated>
        protected Governorate()
        {

        }

        public Governorate(Guid id, string title, Guid iconId, string iconExtension, int order, bool isActive)
            : base(id, title, iconId, iconExtension, order, isActive)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}