using AhlanFeekum.Reservations;
using AhlanFeekum.UserProfiles;
using AhlanFeekum.SiteProperties;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekum.Reservations
{
    public class Reservation : ReservationBase
    {
        //<suite-custom-code-autogenerated>
        protected Reservation()
        {

        }

        public Reservation(Guid id, Guid userProfileId, Guid sitePropertyId, DateOnly fromeDate, DateOnly toDate, double price, ReservationStatus reservationStatus, bool isPaid, DateTime? checkInDate = null, DateTime? checkOutDate = null, int? numberOfGuest = null, double? discount = null, string? notes = null, ReservationPaymentMethod? reservationPaymentMethod = null, string? description = null)
            : base(id, userProfileId, sitePropertyId, fromeDate, toDate, price, reservationStatus, isPaid, checkInDate, checkOutDate, numberOfGuest, discount, notes, reservationPaymentMethod, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}