using AhlanFeekum.Reservations;
using AhlanFeekum.Reservations;
using AhlanFeekum.Reservations;
using AhlanFeekum.Reservations;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekum.Reservations
{
    public class ReservationManager : ReservationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ReservationManager(IReservationRepository reservationRepository)
            : base(reservationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}