using AhlanFeekum.FireBase;
using AhlanFeekum.Permissions;
using AhlanFeekum.Shared;
using AhlanFeekum.Shared;
using AhlanFeekum.SiteProperties;
using AhlanFeekum.UserNotifications;
using AhlanFeekum.UserProfiles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Caching.Distributed;
using MiniExcelLibs;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Volo.Abp.Content;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekum.UserNotifications
{
    public class UserNotificationsAppService : UserNotificationsAppServiceBase, IUserNotificationsAppService
    {
        //<suite-custom-code-autogenerated>
        protected IFcmNotificationsAppService _fcmNotificationsAppService { get; set; }
        public UserNotificationsAppService(IUserNotificationRepository userNotificationRepository, UserNotificationManager userNotificationManager, IDistributedCache<UserNotificationDownloadTokenCacheItem, string> downloadTokenCache, IRepository<AhlanFeekum.UserProfiles.UserProfile, Guid> userProfileRepository, IRepository<AhlanFeekum.SiteProperties.SiteProperty, Guid> sitePropertyRepository, IFcmNotificationsAppService fcmNotificationsAppService)
            : base(userNotificationRepository, userNotificationManager, downloadTokenCache, userProfileRepository, sitePropertyRepository)
        {
            _fcmNotificationsAppService = fcmNotificationsAppService;
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...

        [Authorize(AhlanFeekumPermissions.UserNotifications.Create)]
        public virtual async Task<bool> SendAsync(UserNotificationWithNavigationPropertiesDto input)
        {
            await _fcmNotificationsAppService.SendNotification(input);
            return true;
        }
    }
}