using AhlanFeekum.Shared;
using AhlanFeekum.SiteProperties;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekum.Permissions;
using AhlanFeekum.PropertyCalendars;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekum.Shared;
using AhlanFeekum.MobileResponses;
using AhlanFeekum.Reservations;

namespace AhlanFeekum.PropertyCalendars
{
    public class PropertyCalendarsAppService : PropertyCalendarsAppServiceBase, IPropertyCalendarsAppService
    {
        private readonly IReservationRepository _reservationRepository;

        //<suite-custom-code-autogenerated>
        public PropertyCalendarsAppService(IPropertyCalendarRepository propertyCalendarRepository, PropertyCalendarManager propertyCalendarManager, IDistributedCache<PropertyCalendarDownloadTokenCacheItem, string> downloadTokenCache, IRepository<AhlanFeekum.SiteProperties.SiteProperty, Guid> sitePropertyRepository, IReservationRepository reservationRepository)
            : base(propertyCalendarRepository, propertyCalendarManager, downloadTokenCache, sitePropertyRepository)
        {
            _reservationRepository = reservationRepository;
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...

        [Authorize(AhlanFeekumPermissions.PropertyCalendars.Create)]
        public virtual async Task<MobileResponseDto> CreateManyAsync(List<PropertyCalendarItemDto> input)
        {
            MobileResponseDto mobileResponseDto = new MobileResponseDto();
            mobileResponseDto.Code = 200;
            mobileResponseDto.Message = "SUCCESS";
            GetPropertyCalendarsInput getPropertyCalendarsInput = new GetPropertyCalendarsInput();
           
            if (  !input.IsNullOrEmpty())
            {
                getPropertyCalendarsInput.SitePropertyId = input[0].PropertyId;
                await DeleteAllAsync(getPropertyCalendarsInput);
                foreach (var item in input)
                {
                    await _propertyCalendarManager.CreateAsync(
                              item.PropertyId , item.Date, item.IsAvailable, item.Price, item.Note
                              );
                }
            }
            mobileResponseDto.Data = true;
            return mobileResponseDto;
        }

        [Authorize(AhlanFeekumPermissions.PropertyCalendars.Edit)]
        public virtual async Task<MobileResponseDto> UpdateManyAsync(List<PropertyCalendarItemDto> input)
        {
            MobileResponseDto mobileResponseDto = new MobileResponseDto();
            mobileResponseDto.Code = 200;
            mobileResponseDto.Message = "SUCCESS";
           
            if (!input.IsNullOrEmpty())
            {
                // Get all existing calendar entries for the property
                var propertyId = input[0].PropertyId;
                var existingCalendars = await _propertyCalendarRepository.GetListWithNavigationPropertiesAsync(
                    filterText: null,
                    dateMin: null,
                    dateMax: null,
                    isAvailable: null,
                    priceMin: null,
                    priceMax: null,
                    note: null,
                    sitePropertyId: propertyId,
                    sorting: null,
                    maxResultCount: int.MaxValue,
                    skipCount: 0
                );

                // Filter by property ID

                foreach (var item in input)
                {
                    // Check if a calendar entry exists for this date
                    var existingEntry = existingCalendars.FirstOrDefault(x => x.PropertyCalendar.Date == item.Date);

                    if (existingEntry != null)
                    {
                        // Update existing entry
                        await _propertyCalendarManager.UpdateAsync(
                            existingEntry.PropertyCalendar.Id,
                            item.PropertyId,
                            item.Date,
                            item.IsAvailable,
                            item.Price,
                            item.Note,
                            existingEntry.PropertyCalendar.ConcurrencyStamp
                        );
                    }
                    else
                    {
                        // Create new entry
                        await _propertyCalendarManager.CreateAsync(
                            item.PropertyId,
                            item.Date,
                            item.IsAvailable,
                            item.Price,
                            item.Note
                        );
                    }
                }
            }
            mobileResponseDto.Data = true;
            return mobileResponseDto;
        }

        [AllowAnonymous]
        public virtual async Task<PagedResultDto<PropertyCalendarMobileDto>> GetListMobileAsync(GetPropertyCalendarsInput input)
        {
            var totalCount = await _propertyCalendarRepository.GetCountAsync(input.FilterText, input.DateMin, input.DateMax, input.IsAvailable, input.PriceMin, input.PriceMax, input.Note, input.SitePropertyId);
            var items = await _propertyCalendarRepository.GetListWithNavigationPropertiesAsync(input.FilterText, input.DateMin, input.DateMax, input.IsAvailable, input.PriceMin, input.PriceMax, input.Note, input.SitePropertyId, input.Sorting, input.MaxResultCount, input.SkipCount);

            return new PagedResultDto<PropertyCalendarMobileDto>
            {
                TotalCount = totalCount,
                Items = ObjectMapper.Map<List<PropertyCalendarWithNavigationProperties>, List<PropertyCalendarMobileDto>>(items)
            };
        }

        [AllowAnonymous]
        public virtual async Task<PagedResultDto<PropertyCalendarStatus>> GetListCalendarStatusAsync(GetPropertyCalendarsInput input)
        {
            var totalCount = await _propertyCalendarRepository.GetCountAsync(input.FilterText, input.DateMin, input.DateMax, input.IsAvailable, input.PriceMin, input.PriceMax, input.Note, input.SitePropertyId);
            var items = await _propertyCalendarRepository.GetListWithNavigationPropertiesAsync(input.FilterText, input.DateMin, input.DateMax, input.IsAvailable, input.PriceMin, input.PriceMax, input.Note, input.SitePropertyId, input.Sorting, input.MaxResultCount, input.SkipCount);

            // Get all reservations for the property within the date range
            List<Reservation> reservations = new List<Reservation>();
            if (input.SitePropertyId.HasValue)
            {
                var allReservations = await _reservationRepository.GetListWithNavigationPropertiesAsync(
                    filterText: null,
                    fromeDateMin: input.DateMin,
                    fromeDateMax: input.DateMax,
                    toDateMin: input.DateMin,
                    toDateMax: input.DateMax,
                    sitePropertyId: input.SitePropertyId.Value,
                    maxResultCount: int.MaxValue,
                    skipCount: 0
                );
                reservations = allReservations.Select(r => r.Reservation).ToList();
            }

            var calendarStatusList = new List<PropertyCalendarStatus>();

            foreach (var item in items)
            {
                var calendar = item.PropertyCalendar;
                var calendarStatus = new PropertyCalendarStatus
                {
                    Id = calendar.Id,
                    Date = calendar.Date,
                    IsAvailable = calendar.IsAvailable,
                    PropertyId = calendar.SitePropertyId,
                    Status = string.Empty
                };

                // Check if there's a reservation for this date
                var reservation = reservations.FirstOrDefault(r =>
                    r.SitePropertyId == calendar.SitePropertyId &&
                    calendar.Date >= r.FromeDate &&
                    calendar.Date <= r.ToDate
                );

                if (reservation != null)
                {
                    // There's a reservation for this date, set status based on reservation status
                    calendarStatus.Status = reservation.ReservationStatus switch
                    {
                        ReservationStatus.Pending => CalendarStatus.PendingReservation.ToString(),
                        ReservationStatus.Approved => CalendarStatus.ApprovedReservation.ToString(),
                        ReservationStatus.NotAvailable => CalendarStatus.NotAvailable.ToString(),
                        _ => CalendarStatus.NotAvailable.ToString()
                    };
                }
                else
                {
                    // No reservation, set status based on calendar availability
                    calendarStatus.Status = calendar.IsAvailable
                        ? CalendarStatus.Available.ToString()
                        : CalendarStatus.NotAvailable.ToString();
                }

                calendarStatusList.Add(calendarStatus);
            }

            return new PagedResultDto<PropertyCalendarStatus>
            {
                TotalCount = totalCount,
                Items = calendarStatusList
            };
        }
    }
}