using AhlanFeekum.Authorizations;
using AhlanFeekum.MobileResponses;
using AhlanFeekum.Permissions;
using AhlanFeekum.Reservations;
using AhlanFeekum.Shared;
using AhlanFeekum.Shared;
using AhlanFeekum.SiteProperties;
using AhlanFeekum.UserPayments;
using AhlanFeekum.UserProfiles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using MiniExcelLibs;
using Stripe;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Net;
using System.Net.Http;
using System.Net.Mail;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Volo.Abp.Content;
using Volo.Abp.Domain.Repositories;
using Volo.Abp.Emailing;
using Volo.Abp.Identity;
using Volo.Abp.Users;
using static Volo.Abp.Identity.Settings.IdentitySettingNames;

namespace AhlanFeekum.UserProfiles
{
    public class UserProfilesAppService : UserProfilesAppServiceBase, IUserProfilesAppService
    {
        //<suite-custom-code-autogenerated>
        public UserManager _userManager { get; set; }
        protected Microsoft.Extensions.Configuration.IConfiguration _configuration;
        protected HttpClient _httpClient;
        protected IEmailSender _emailSender;
        public ICurrentUser _currentUser { get; set; }
        private readonly ILogger<UserProfilesAppService> _logger;

        private IUserPaymentsAppService _userPaymentsAppService { get; set; }
        private IReservationRepository _reservationRepository { get; set; }
        private IReservationsAppService _reservationsAppService { get; set; }
        private IUserPaymentRepository _userPaymentRepository { get; set; }
        public UserProfilesAppService(IUserProfileRepository userProfileRepository, UserProfileManager userProfileManager, IDistributedCache<UserProfileDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Volo.Abp.Identity.IdentityRole, Guid> identityRoleRepository, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository, UserManager userManager,
            Microsoft.Extensions.Configuration.IConfiguration configuration, HttpClient httpClient, IEmailSender emailSender, ICurrentUser currentUser, ILogger<UserProfilesAppService> logger, IUserPaymentsAppService userPaymentsAppService, IReservationsAppService reservationsAppService, IReservationRepository reservationRepository, IUserPaymentRepository userPaymentRepository)
            : base(userProfileRepository, userProfileManager, downloadTokenCache, identityRoleRepository, identityUserRepository)
        {
            _userManager = userManager;
            _configuration = configuration;
            _httpClient = httpClient;
            _emailSender = emailSender;
            _currentUser = currentUser;
            _logger = logger;
            _userPaymentsAppService = userPaymentsAppService;
            _reservationsAppService = reservationsAppService;
            _reservationRepository = reservationRepository;
            _userPaymentRepository = userPaymentRepository;
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
        [AllowAnonymous]
        public virtual async Task<MobileResponseDto> RegisterAsync(RegisterCreateMobileDto input)
        {
            var user = await _userProfileManager.CreatWithDetialsAsync(input.Name, input.IsSuperHost, input.Password, input.ProfilePhoto, input.RoleId, input.Email, input.PhoneNumber, input.Latitude, input.Longitude, input.Address);
            return ObjectMapper.Map<MobileResponse, MobileResponseDto>(user);
        }

        [AllowAnonymous]
        public virtual async Task<MobileResponseDto> UpdateMyProfileAsync(UserProfileUpdateMobileDto input)
        {
            if(_currentUser == null)
                throw new UserFriendlyException("User not login");
            var user = await _userProfileManager.UpdateMyProfileAsync(_currentUser.Id.Value, input.Name, input.ProfilePhoto, input.IsProfilePhotoChanged, input.Email, input.PhoneNumber, input.Latitude, input.Longitude, input.Address);
            return ObjectMapper.Map<MobileResponse, MobileResponseDto>(user);
        }
        [AllowAnonymous]
        public virtual async Task<MobileResponseDto> RequestPasswordResetAsync(PasswordResetRequestDto input)
        {
            GetUserProfilesInput getUserProfilesInput = new GetUserProfilesInput();
            int type = 2;
            getUserProfilesInput.Email = input.EmailOrPhone;
            var users = await GetListAsync(getUserProfilesInput);

            MobileResponseDto mobileResponse = new MobileResponseDto();
            if (users.TotalCount == 0)
            {
                getUserProfilesInput = new GetUserProfilesInput();
                getUserProfilesInput.PhoneNumber = input.EmailOrPhone;
                users = await GetListAsync(getUserProfilesInput);
                if (users.TotalCount == 0)
                    throw new UserFriendlyException("User not found with this email address.");
                else
                    type = 1;
            }
            else
                type = 0;
            var firstUser = users.Items.FirstOrDefault();
            var user = firstUser.IdentityUser;

            // Generate a random security code
            Random random = new Random();
            string securityCode = random.Next(1000, 10000).ToString();

            // Store the security code in cache with expiration
            var cacheKey = $"password_reset_{user.Id}";
            await _downloadTokenCache.SetAsync(
                cacheKey,
                new UserProfileDownloadTokenCacheItem { SecurityCode = securityCode },
                new DistributedCacheEntryOptions { AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(5) }
            );

            // TODO: Send security code via email or SMS

            //Email Send
            if (type == 0)
            {
                if (input.EmailOrPhone.IsNullOrWhiteSpace())
                {
                    mobileResponse.Code = 400;
                    mobileResponse.Message = "Email is required";
                    mobileResponse.Data = null;
                    return mobileResponse;
                }

                var smtpSection = _configuration.GetSection("Email:Smtp");
                var emailSection = _configuration.GetSection("Email");
                using (var client = new SmtpClient(smtpSection["Host"], smtpSection["Port"] != null ? int.Parse(smtpSection["Port"]) : 587))
                {
                    client.EnableSsl = true;
                    client.UseDefaultCredentials = false;
                    client.Credentials = new NetworkCredential(smtpSection["UserName"], smtpSection["Password"]);

                    var mailMessage = new MailMessage
                    {
                        From = new MailAddress(emailSection["DefaultFromAddress"], emailSection["DefaultFromDisplayName"]),
                        Subject = "Security Code",
                        Body = $"<h1>{securityCode}</h1>",
                        IsBodyHtml = true
                    };

                    mailMessage.To.Add(input.EmailOrPhone);

                    await client.SendMailAsync(mailMessage);
                    mobileResponse.Code = 200;
                    mobileResponse.Message = "Success";
                    mobileResponse.Data = "Success";
                    return mobileResponse;
                }
            }
            else
            {
                //SMS SEND SECURITY CODE
                return mobileResponse;
            }
        }

        [AllowAnonymous]
        public virtual async Task<MobileResponseDto> ConfirmPasswordResetAsync(PasswordConfirmResetRequestDto input)
        {
            GetUserProfilesInput getUserProfilesInput = new GetUserProfilesInput();
            getUserProfilesInput.Email = input.EmailOrPhone;
            var users = await GetListAsync(getUserProfilesInput);

            MobileResponseDto mobileResponse = new MobileResponseDto();
            if (users.TotalCount == 0)
            {
                getUserProfilesInput = new GetUserProfilesInput();
                getUserProfilesInput.PhoneNumber = input.EmailOrPhone;
                users = await GetListAsync(getUserProfilesInput);
                if (users.TotalCount == 0)
                    throw new UserFriendlyException("User not found with this email address.");
            }
            var firstUser = users.Items.FirstOrDefault();
            var user = firstUser.IdentityUser;

            //var user = await _userManager.FindByEmailAsync(input.EmailOrPhone);
            //if (user == null)
            //{
            //    var user = await _userManager.FindByEmailAsync(input.EmailOrPhone);
            //    throw new UserFriendlyException("User not found with this email address.");
            //}

            // Verify security code from cache
            var cacheKey = $"password_reset_{user.Id}";
            var cacheItem = await _downloadTokenCache.GetAsync(cacheKey);

            if (cacheItem == null || cacheItem.SecurityCode != input.SecurityCode)
            {
                throw new UserFriendlyException("Invalid or expired security code.");
            }

            // Generate reset token and reset password
            //var token = await _userManager.GeneratePasswordResetTokenForEmailAsync(input.Email);
            //await _userManager.ResetPasswordForEmailAsync(input.Email, token, input.NewPassword);


            await _userManager.ResetPasswordWithoutTokenAsync(user.Email, input.NewPassword);

            // Remove the security code from cache
            await _downloadTokenCache.RemoveAsync(cacheKey);

            var response = new MobileResponse
            {
                Code = 200,
                Message = "Password reset successfully",
                Data = null
            };

            return ObjectMapper.Map<MobileResponse, MobileResponseDto>(response);
        }


        //[AllowAnonymous]
        //public virtual async Task<MobileResponseDto> ResetPasswordWithoutTokenAsync(PasswordResetRequestDto input)
        //{
        //    var user = await _userManager.FindByEmailAsync(input.Email);
        //    if (user == null)
        //    {
        //        throw new UserFriendlyException("User not found with this email address.");
        //    }


        //    // Generate reset token and reset password
        //    await _userManager.ResetPasswordWithoutTokenAsync(input.Email, input.NewPassword);

        //    var response = new MobileResponse
        //    {
        //        Code = 200,
        //        Message = "Password reset successfully",
        //        Data = null
        //    };

        //    return ObjectMapper.Map<MobileResponse, MobileResponseDto>(response);
        //}

        [AllowAnonymous]
        public virtual async Task<MobileResponseDto> ChangePasswordAsync(PasswordChangeRequestDto input)
        {
            var user = await _userManager.FindByEmailAsync(input.EmailOrPhone);
            if (user == null)
            {
                throw new UserFriendlyException("User not found with this email address.");
            }

            // Generate reset token and reset password
            await _userManager.ChangePasswordAsync(input.EmailOrPhone, input.OldPassword, input.NewPassword);

            var response = new MobileResponse
            {
                Code = 200,
                Message = "Password reset successfully",
                Data = null
            };

            return ObjectMapper.Map<MobileResponse, MobileResponseDto>(response);
        }


        [AllowAnonymous]
        public async Task<MobileResponseDto> SendSecretKeyEmailAsync(string input)
        {
            MobileResponseDto mobileResponse = new MobileResponseDto();
            try
            {
                if (input.IsNullOrWhiteSpace())
                {
                    mobileResponse.Code = 400;
                    mobileResponse.Message = "Email is required";
                    mobileResponse.Data = null;
                    return mobileResponse;
                }
                Random random = new Random();
                int securityNum = random.Next(1000, 10000);

                var smtpSection = _configuration.GetSection("Email:Smtp");
                var emailSection = _configuration.GetSection("Email");
                using (var client = new SmtpClient(smtpSection["Host"], smtpSection["Port"] != null ? int.Parse(smtpSection["Port"]) : 587))
                {
                    client.EnableSsl = true;
                    client.UseDefaultCredentials = false;
                    client.Credentials = new NetworkCredential(smtpSection["UserName"], smtpSection["Password"]);

                    var mailMessage = new MailMessage
                    {
                        From = new MailAddress(emailSection["DefaultFromAddress"], emailSection["DefaultFromDisplayName"]),
                        Subject = "Security Code",
                        Body = $"<h1>{securityNum.ToString()}</h1>",
                        IsBodyHtml = true
                    };

                    mailMessage.To.Add(input);

                    var cacheKey = $"email_verify_{input}";
                    var cacheItem = await _downloadTokenCache.GetAsync(cacheKey);

                    if (cacheItem != null)
                        await _downloadTokenCache.RemoveAsync(cacheKey);


                    await _downloadTokenCache.SetAsync(
                        cacheKey,
                        new UserProfileDownloadTokenCacheItem { SecurityCode = securityNum.ToString() },
                        new DistributedCacheEntryOptions { AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(5) }
                    );

                    await client.SendMailAsync(mailMessage);
                    mobileResponse.Code = 200;
                    mobileResponse.Message = "Success";
                    mobileResponse.Data = "Success";
                    return mobileResponse;
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
                mobileResponse.Code = 501;
                mobileResponse.Message = "Failed to send Email message.";
                mobileResponse.Data = null;
                return mobileResponse;
            }


            mobileResponse.Code = 501;
            mobileResponse.Message = "Failed to send Email message.";
            mobileResponse.Data = null;
            return mobileResponse;
        }
        [AllowAnonymous]
        public virtual async Task<MobileResponseDto> VerifyAsync(VerifyRequestDto input)
        {
            MobileResponseDto mobileResponse = new MobileResponseDto()
            {
                Code = 200,
                Data = true,
                Message = "SUCCESS"
            };
            var cacheKey = $"email_verify_{input.EmailOrPhone}";
            var cacheItem = await _downloadTokenCache.GetAsync(cacheKey);

            if (cacheItem == null || cacheItem.SecurityCode != input.SecurityCode)
            {
                throw new UserFriendlyException("Invalid or expired security code.");
            }
            else
            {
                await _downloadTokenCache.RemoveAsync(cacheKey);
                return mobileResponse;
            }

               

        }
        [AllowAnonymous]
        public async Task<MobileResponseDto> SendSecretKeyPhoneAsync(string input)
        {
            MobileResponseDto mobileResponse = new MobileResponseDto();
            try
            {
                if (input.IsNullOrWhiteSpace())
                {
                    mobileResponse.Code = 400;
                    mobileResponse.Message = "Phone is required";
                    mobileResponse.Data = null;
                    return mobileResponse;
                }
                Random random = new Random();
                int securityNum = random.Next(1000, 10000);

                // Send security code via WhatsApp API
                var whatsappSection = _configuration.GetSection("WhatsApp");
                var apiKey = whatsappSection["ApiKey"];
                var apiUrl = whatsappSection["ApiUrl"]; ;
                var fromNumber = whatsappSection["DefaultPhoneNumber"];

                // Prepare WhatsApp message
                var whatsappMessage = new
                {
                    messageType = "text",
                    requestType = "POST",
                    token = apiKey,
                    from = fromNumber,
                    to = input,
                    text = $" is: {securityNum}"
                };

                // Cache the security code
                var cacheKey = $"phone_verify_{input}";
                var cacheItem = await _downloadTokenCache.GetAsync(cacheKey);

                if (cacheItem != null)
                    await _downloadTokenCache.RemoveAsync(cacheKey);

                await _downloadTokenCache.SetAsync(
                    cacheKey,
                    new UserProfileDownloadTokenCacheItem { SecurityCode = securityNum.ToString() },
                    new DistributedCacheEntryOptions { AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(5) }
                );

                // Send WhatsApp message
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {apiKey}");
                    
                    var json = System.Text.Json.JsonSerializer.Serialize(whatsappMessage);
                    var content = new StringContent(json, System.Text.Encoding.UTF8, "application/json");
                    
                    var response = await httpClient.PostAsync(apiUrl, content);
                    
                    if (response.IsSuccessStatusCode)
                    {
                        mobileResponse.Code = 200;
                        mobileResponse.Message = "Success";
                        mobileResponse.Data = "Security code sent via WhatsApp";
                        return mobileResponse;
                    }
                    else
                    {
                        var errorContent = await response.Content.ReadAsStringAsync();
                        throw new Exception($"WhatsApp API error: {response.StatusCode} - {errorContent}");
                    }
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
                mobileResponse.Code = 501;
                mobileResponse.Message = "Failed to send WhatsApp message.";
                mobileResponse.Data = null;
                return mobileResponse;
            }


            mobileResponse.Code = 501;
            mobileResponse.Message = "Failed to send WhatsApp message.";
            mobileResponse.Data = null;
            return mobileResponse;

        }


        [AllowAnonymous]
        public virtual async Task<MobileResponseDto> VerifyPhoneAsync(PhoneVerifyRequestDto input)
        {
            MobileResponseDto mobileResponse = new MobileResponseDto()
            {
                Code = 200,
                Data = true,
                Message = "SUCCESS"
            };
            var cacheKey = $"phone_verify_{input.Phone}";
            var cacheItem = await _downloadTokenCache.GetAsync(cacheKey);

            if (cacheItem == null || cacheItem.SecurityCode != input.SecurityCode)
            {
                throw new UserFriendlyException("Invalid or expired security code.");
            }
            else
            {
                await _downloadTokenCache.RemoveAsync(cacheKey);
                return mobileResponse;
            }
        }

        [AllowAnonymous]
        public virtual async Task<HomePageDto> GetHomePageAsync()
        {
            Guid? userId = null;
            if (_currentUser == null)
                userId = null;
            else
                userId = _currentUser.Id;
                return ObjectMapper.Map<HomePage, HomePageDto>(await _userProfileRepository.GetHomePageAsync(userId));
        }

        public virtual async Task<UserProfileWithDetailsMobileDto> GetWithDetailsAsync(Guid? id)
        {

            Guid? userId = null;
            if (id == null)
            {
                if (_currentUser == null)
                    throw new UserFriendlyException("No User Selected");
                userId = _currentUser.Id;
            }
            else
                userId = id;

            return ObjectMapper.Map<UserProfileWithDetails, UserProfileWithDetailsMobileDto>(await _userProfileRepository.GetWithDetailsAsync(userId.Value));

        }

        #region Stripe Payment Methods

        /// <summary>
        /// Creates a new Stripe PaymentIntent
        /// </summary>
        [Authorize(AhlanFeekumPermissions.UserPayments.Create)]
        public virtual async Task<PaymentIntentResponseDto> CreatePaymentIntentAsync(CreatePaymentIntentDto input)
        {
            try
            {
                if (_currentUser == null)
                    throw new UserFriendlyException("User not login");

                if (input.Metadata == null || input.Metadata["bookingId"] == null)
                    throw new UserFriendlyException("ReservationIsRequired");
                Guid reservationId = Guid.Parse(input.Metadata["bookingId"]);

                if(!(await _reservationRepository.AnyAsync(x=>x.Id== reservationId)))
                    throw new UserFriendlyException("ReservationNotFound");
                // Set the Stripe API key from configuration
                var stripeSection = _configuration.GetSection("Stripe");
                StripeConfiguration.ApiKey = stripeSection["SecretKey"];

                var options = new PaymentIntentCreateOptions
                {
                    Amount = input.Amount,
                    Currency = input.Currency.ToLower(),
                    AutomaticPaymentMethods = new PaymentIntentAutomaticPaymentMethodsOptions
                    {
                        Enabled = true,
                    },
                    Description = input.Description,
                    ReceiptEmail = input.ReceiptEmail,
                    Metadata = input.Metadata ?? new Dictionary<string, string>()
                };

                // Add user ID to metadata if provided
                if (input.UserId.HasValue)
                {
                    options.Metadata["user_id"] = input.UserId.Value.ToString();
                }

                var service = new PaymentIntentService();
                var paymentIntent = await service.CreateAsync(options);

                UserPaymentCreateDto userPaymentCreateDto = new UserPaymentCreateDto()
                {
                    Amount = paymentIntent.Amount,
                    Currency = paymentIntent.Currency.ToLower(),
                    StripClientSecret = paymentIntent.ClientSecret,
                    StripPaymentId = paymentIntent.Id,
                    ReceiptEmail = paymentIntent.ReceiptEmail,
                    Status = UserPaymentStatus.Pending,
                    UserProfileId = _currentUser.Id.Value,
                    ReservationId = reservationId,
                };
                await _userPaymentsAppService.CreateAsync(userPaymentCreateDto);
                return MapPaymentIntentToDto(paymentIntent);
            }
            catch (StripeException ex)
            {
                throw new UserFriendlyException($"Stripe error: {ex.Message}");
            }
            catch (Exception ex)
            {
                throw new UserFriendlyException($"Payment creation failed: {ex.Message}");
            }
        }

        /// <summary>
        /// Retrieves an existing PaymentIntent
        /// </summary>
        [AllowAnonymous]
        public virtual async Task<PaymentIntentResponseDto> GetPaymentIntentAsync(string paymentIntentId)
        {
            try
            {
                // Set the Stripe API key from configuration
                var stripeSection = _configuration.GetSection("Stripe");
                StripeConfiguration.ApiKey = stripeSection["SecretKey"];

                var service = new PaymentIntentService();
                var paymentIntent = await service.GetAsync(paymentIntentId);

                return MapPaymentIntentToDto(paymentIntent);
            }
            catch (StripeException ex)
            {
                throw new UserFriendlyException($"Stripe error: {ex.Message}");
            }
            catch (Exception ex)
            {
                throw new UserFriendlyException($"Failed to retrieve payment: {ex.Message}");
            }
        }

        /// <summary>
        /// Confirms a PaymentIntent
        /// </summary>
        [Authorize(AhlanFeekumPermissions.UserPayments.Create)]
        public virtual async Task<PaymentIntentResponseDto> ConfirmPaymentIntentAsync(ConfirmPaymentDto input)
        {
            try
            {
                // Set the Stripe API key from configuration
                var stripeSection = _configuration.GetSection("Stripe");
                StripeConfiguration.ApiKey = stripeSection["SecretKey"];

                var options = new PaymentIntentConfirmOptions
                {
                    PaymentMethod = input.PaymentMethodId,
                    ReturnUrl = stripeSection["ReturnUrl"] // For redirect-based payment methods
                };

                var service = new PaymentIntentService();
                var paymentIntent = await service.ConfirmAsync(input.PaymentIntentId, options);

                if(paymentIntent.Status != null && paymentIntent.Status.ToLower() == "succeeded")
                {
                    GetUserPaymentsInput getUserPaymentsInput = new GetUserPaymentsInput()
                    {
                        StripClientSecret = paymentIntent.ClientSecret,
                        StripPaymentId = paymentIntent.Id,
                        SkipCount = 0,
                        MaxResultCount = 1
                    };
                    var payments = await _userPaymentsAppService.GetListAsync(getUserPaymentsInput);
                    if(payments.TotalCount > 0)
                    {
                        var payment = payments.Items.FirstOrDefault();
                        var updatePayment = ObjectMapper.Map<UserPaymentDto, UserPaymentUpdateDto>(payment.UserPayment);
                        updatePayment.Status = UserPaymentStatus.succeeded;
                        updatePayment.Description = paymentIntent.Description;
                        updatePayment.AmountCapturable = paymentIntent.AmountCapturable;
                        updatePayment.AmountReceived = paymentIntent.AmountReceived;
                        await _userPaymentsAppService.UpdateAsync(payment.UserPayment.Id, updatePayment);
                        Reservation reservation = await _reservationRepository.GetAsync(payment.Reservation.Id);
                        reservation.ReservationStatus = ReservationStatus.Approved;
                        await _reservationRepository.UpdateAsync(reservation, autoSave: true);
                    }
                }
                return MapPaymentIntentToDto(paymentIntent);
            }
            catch (StripeException ex)
            {
                throw new UserFriendlyException($"Stripe error: {ex.Message}");
            }
            catch (Exception ex)
            {
                throw new UserFriendlyException($"Payment confirmation failed: {ex.Message}");
            }
        }

        /// <summary>
        /// Handles Stripe webhook events
        /// </summary>
        [AllowAnonymous]
        public virtual async Task<StripeWebhookEventDto> HandleStripeWebhookAsync(string json, string stripeSignature)
        {
            try
            {
                // Set the Stripe API key from configuration
                var stripeSection = _configuration.GetSection("Stripe");
                StripeConfiguration.ApiKey = stripeSection["SecretKey"];
                var webhookSecret = stripeSection["WebhookSecret"];

                if (string.IsNullOrEmpty(webhookSecret))
                {
                    throw new UserFriendlyException("Webhook secret is not configured.");
                }

                // Verify the webhook signature
                var stripeEvent = EventUtility.ConstructEvent(
                    json,
                    stripeSignature,
                    webhookSecret,
                    throwOnApiVersionMismatch: false
                );

                // Log the event
                _logger.LogInformation("Stripe webhook received: {EventType}", stripeEvent.Type);



                string tttt = stripeEvent.Type;
                var successIntent = stripeEvent.Data.Object as PaymentIntent;
                    await HandlePaymentSucceededAsync(successIntent);
                    return MapWebhookEventToDto(stripeEvent, successIntent);

                // Handle different event types
                switch (stripeEvent.Type)
                {

                    //case Events.PaymentIntentSucceeded:
                    //    var successIntent = stripeEvent.Data.Object as PaymentIntent;
                    //    await HandlePaymentSucceededAsync(successIntent);
                    //    return MapWebhookEventToDto(stripeEvent, successIntent);

                    //case Events.PaymentIntentPaymentFailed:
                    //    var failedIntent = stripeEvent.Data.Object as PaymentIntent;
                    //    await HandlePaymentFailedAsync(failedIntent);
                    //    return MapWebhookEventToDto(stripeEvent, failedIntent);

                    //case Events.PaymentIntentCanceled:
                    //    var canceledIntent = stripeEvent.Data.Object as PaymentIntent;
                    //    await HandlePaymentCanceledAsync(canceledIntent);
                    //    return MapWebhookEventToDto(stripeEvent, canceledIntent);

                    //case Events.PaymentIntentCreated:
                    //    var createdIntent = stripeEvent.Data.Object as PaymentIntent;
                    //    return MapWebhookEventToDto(stripeEvent, createdIntent);

                    //default:
                    //    _logger.LogInformation("Unhandled webhook event type: {EventType}", stripeEvent.Type);
                    //    return new StripeWebhookEventDto { EventType = stripeEvent.Type };
                }
            }
            catch (StripeException ex)
            {
                _logger.LogError(ex, "Stripe webhook signature verification failed");
                throw new UserFriendlyException($"Invalid webhook signature: {ex.Message}");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error processing webhook");
                throw new UserFriendlyException($"Webhook processing failed: {ex.Message}");
            }
        }

        /// <summary>
        /// Handles successful payment
        /// </summary>
        private async Task HandlePaymentSucceededAsync(PaymentIntent paymentIntent)
        {
            _logger.LogInformation("Payment succeeded for PaymentIntent: {PaymentIntentId}, Amount: {Amount}", 
                paymentIntent.Id, paymentIntent.Amount);

            // Add your business logic here:
            // - Update order status in database
            // - Send confirmation email
            // - Update user profile (e.g., subscription status)
            // - Trigger fulfillment process
            
            // Example: Get user ID from metadata
            if (paymentIntent.Metadata?.ContainsKey("user_id") == true)
            {
                var userId = paymentIntent.Metadata["user_id"];
                _logger.LogInformation("Payment for user: {UserId}", userId);
                
                // TODO: Add your custom logic here
                // e.g., update booking status, credit account, etc.
            }

            await Task.CompletedTask;
        }

        /// <summary>
        /// Handles failed payment
        /// </summary>
        private async Task HandlePaymentFailedAsync(PaymentIntent paymentIntent)
        {
            _logger.LogWarning("Payment failed for PaymentIntent: {PaymentIntentId}", paymentIntent.Id);

            // Add your business logic here:
            // - Notify user of payment failure
            // - Update order status
            // - Send retry payment link
            
            if (paymentIntent.Metadata?.ContainsKey("user_id") == true)
            {
                var userId = paymentIntent.Metadata["user_id"];
                _logger.LogInformation("Failed payment for user: {UserId}", userId);
                
                // TODO: Send notification to user
            }

            await Task.CompletedTask;
        }

        /// <summary>
        /// Handles canceled payment
        /// </summary>
        private async Task HandlePaymentCanceledAsync(PaymentIntent paymentIntent)
        {
            _logger.LogInformation("Payment canceled for PaymentIntent: {PaymentIntentId}", paymentIntent.Id);

            // Add your business logic here:
            // - Update order status to canceled
            // - Free up reserved inventory
            // - Notify user
            
            await Task.CompletedTask;
        }

        /// <summary>
        /// Maps Stripe PaymentIntent to DTO
        /// </summary>
        private PaymentIntentResponseDto MapPaymentIntentToDto(PaymentIntent paymentIntent)
        {
            return new PaymentIntentResponseDto
            {
                Id = paymentIntent.Id,
                Object = paymentIntent.Object,
                Amount = paymentIntent.Amount,
                AmountCapturable = paymentIntent.AmountCapturable,
                AmountReceived = paymentIntent.AmountReceived,
                ClientSecret = paymentIntent.ClientSecret,
                ConfirmationMethod = paymentIntent.ConfirmationMethod,
                Created = new DateTimeOffset(paymentIntent.Created).ToUnixTimeSeconds(),
                Currency = paymentIntent.Currency,
                Customer = paymentIntent.CustomerId,
                Description = paymentIntent.Description,
                Status = paymentIntent.Status,
                Metadata = paymentIntent.Metadata?.ToDictionary(x => x.Key, x => x.Value) ?? new Dictionary<string, string>(),
                ReceiptEmail = paymentIntent.ReceiptEmail,
                PaymentMethodTypes = paymentIntent.PaymentMethodTypes?.ToList() ?? new List<string>()
            };
        }

        /// <summary>
        /// Maps Stripe event to webhook DTO
        /// </summary>
        private StripeWebhookEventDto MapWebhookEventToDto(Event stripeEvent, PaymentIntent paymentIntent)
        {
            if (paymentIntent == null)
            {
                return new StripeWebhookEventDto
                {
                    EventType = stripeEvent.Type
                };
            }

            return new StripeWebhookEventDto
            {
                EventType = stripeEvent.Type,
                PaymentIntentId = paymentIntent.Id,
                Status = paymentIntent.Status,
                Amount = paymentIntent.Amount,
                Currency = paymentIntent.Currency,
                Metadata = paymentIntent.Metadata?.ToDictionary(x => x.Key, x => x.Value) ?? new Dictionary<string, string>(),
                CustomerId = paymentIntent.CustomerId,
                ReceiptEmail = paymentIntent.ReceiptEmail
            };
        }

        /// <summary>
        /// Gets payment summary for the current user grouped by month
        /// </summary>
        [Authorize]
        public virtual async Task<PaymentSummaryResponseDto> GetPaymentSummaryAsync(PaymentSummaryRequestDto input)
        {
            try
            {
                if (_currentUser == null || !_currentUser.Id.HasValue)
                    throw new UserFriendlyException("User not logged in");

                // Validate date range
                if (input.EndDate < input.StartDate)
                    throw new UserFriendlyException("End date must be greater than or equal to start date");

                // Get all successful payments for the current user within the date range
                var queryable = await _userPaymentRepository.GetQueryableAsync();
                
                var payments = await AsyncExecuter.ToListAsync(
                    queryable
                        .Where(p => p.UserProfileId == _currentUser.Id.Value)
                        .Where(p => p.Status == UserPaymentStatus.succeeded)
                        .Where(p => p.CreationTime >= input.StartDate && p.CreationTime <= input.EndDate)
                        .OrderBy(p => p.CreationTime)
                );

                if (!payments.Any())
                {
                    return new PaymentSummaryResponseDto
                    {
                        MonthlyPayments = new Dictionary<string, decimal>(),
                        TotalPayment = 0,
                        Currency = "usd",
                        PaymentCount = 0
                    };
                }

                // Group payments by month and calculate totals
                var monthlyPayments = payments
                    .GroupBy(p => new DateTime(p.CreationTime.Year, p.CreationTime.Month, 1))
                    .OrderBy(g => g.Key)
                    .ToDictionary(
                        g => g.Key.ToString("yyyy-MM"),
                        g => g.Sum(p => p.Amount / 100m) // Convert from cents to dollars
                    );

                // Calculate total payment
                var totalPayment = payments.Sum(p => p.Amount / 100m); // Convert from cents to dollars

                // Get the most common currency (in case there are multiple)
                var currency = payments
                    .GroupBy(p => p.Currency)
                    .OrderByDescending(g => g.Count())
                    .First()
                    .Key;

                return new PaymentSummaryResponseDto
                {
                    MonthlyPayments = monthlyPayments,
                    TotalPayment = totalPayment,
                    Currency = currency,
                    PaymentCount = payments.Count
                };
            }
            catch (UserFriendlyException)
            {
                throw;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error retrieving payment summary for user {UserId}", _currentUser?.Id);
                throw new UserFriendlyException($"Failed to retrieve payment summary: {ex.Message}");
            }
        }

        #endregion

    }
}