using AhlanFeekum.CashPayments;
using AhlanFeekum.UserProfiles;
using AhlanFeekum.Reservations;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekum.CashPayments
{
    public class CashPayment : CashPaymentBase
    {
        //<suite-custom-code-autogenerated>
        protected CashPayment()
        {

        }

        public CashPayment(Guid id, Guid userProfileId, Guid reservationId, long amount, string currency, DateTime paymentDate, CashPaymentStatus status, string? description = null)
            : base(id, userProfileId, reservationId, amount, currency, paymentDate, status, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}