using AhlanFeekum.CashPayments;
using AhlanFeekum.CashPayments;
using AhlanFeekum.CashPayments;
using AhlanFeekum.CashPayments;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekum.CashPayments
{
    public class CashPaymentManager : CashPaymentManagerBase
    {
        //<suite-custom-code-autogenerated>
        public CashPaymentManager(ICashPaymentRepository cashPaymentRepository)
            : base(cashPaymentRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}