using AhlanFeekum.UserProfiles;
using AhlanFeekum.SiteProperties;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekum.UserNotifications
{
    public class UserNotificationManager : UserNotificationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public UserNotificationManager(IUserNotificationRepository userNotificationRepository,
        IRepository<UserProfile, Guid> userProfileRepository,
        IRepository<SiteProperty, Guid> sitePropertyRepository)
            : base(userNotificationRepository, userProfileRepository, sitePropertyRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}