using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekum.UserNotifications
{
    public class UserNotification : UserNotificationBase
    {
        //<suite-custom-code-autogenerated>
        protected UserNotification()
        {

        }

        public UserNotification(Guid id, string title, string body)
            : base(id, title, body)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}