using AhlanFeekum.Shared;
using AhlanFeekum.SiteProperties;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekum.Permissions;
using AhlanFeekum.PropertyMedias;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekum.Shared;

namespace AhlanFeekum.PropertyMedias
{
    public class PropertyMediasAppService : PropertyMediasAppServiceBase, IPropertyMediasAppService
    {
        //<suite-custom-code-autogenerated>
        public PropertyMediasAppService(IPropertyMediaRepository propertyMediaRepository, PropertyMediaManager propertyMediaManager, IDistributedCache<PropertyMediaDownloadTokenCacheItem, string> downloadTokenCache, IRepository<AhlanFeekum.SiteProperties.SiteProperty, Guid> sitePropertyRepository)
            : base(propertyMediaRepository, propertyMediaManager, downloadTokenCache, sitePropertyRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}