using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekum.Statuses
{
    public class StatusManager : StatusManagerBase
    {
        //<suite-custom-code-autogenerated>
        public StatusManager(IStatusRepository statusRepository)
            : base(statusRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}