using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekum.Statuses
{
    public class Status : StatusBase
    {
        //<suite-custom-code-autogenerated>
        protected Status()
        {

        }

        public Status(Guid id, string name, int order, bool isActive)
            : base(id, name, order, isActive)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}