using AhlanFeekum.Shared;
using AhlanFeekum.UserProfiles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekum.Permissions;
using AhlanFeekum.Tickets;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekum.Shared;
using Volo.Abp.Clients;
using Volo.Abp.Users;

namespace AhlanFeekum.Tickets
{
    public class TicketsAppService : TicketsAppServiceBase, ITicketsAppService
    {
        public ICurrentUser _currentUser { get; set; }
        //<suite-custom-code-autogenerated>
        public TicketsAppService(ITicketRepository ticketRepository, TicketManager ticketManager, IDistributedCache<TicketDownloadTokenCacheItem, string> downloadTokenCache, IRepository<AhlanFeekum.UserProfiles.UserProfile, Guid> userProfileRepository, ICurrentUser currentUser)
            : base(ticketRepository, ticketManager, downloadTokenCache, userProfileRepository)
        {
            _currentUser = currentUser;
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...

        [Authorize(AhlanFeekumPermissions.Tickets.Create)]
        [RemoteService(false)]
        public virtual async Task<TicketDto> CreateAsync(TicketCreateMobileDto input)
        {
            Guid? userId = null;
            if(_currentUser != null)
                userId = _currentUser.Id;
            var ticket = await _ticketManager.CreateAsync(
            userId, input.FirstName, input.LastName, input.Description, false
            );

            return ObjectMapper.Map<Ticket, TicketDto>(ticket);
        }
    }
}