using AhlanFeekum.Shared;
using AhlanFeekum.PropertyFeatures;
using AhlanFeekum.PropertyTypes;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekum.Permissions;
using AhlanFeekum.SiteProperties;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekum.Shared;

namespace AhlanFeekum.SiteProperties
{
    public class SitePropertiesAppService : SitePropertiesAppServiceBase, ISitePropertiesAppService
    {
        //<suite-custom-code-autogenerated>
        public SitePropertiesAppService(ISitePropertyRepository sitePropertyRepository, SitePropertyManager sitePropertyManager, IDistributedCache<SitePropertyDownloadTokenCacheItem, string> downloadTokenCache, IRepository<AhlanFeekum.PropertyTypes.PropertyType, Guid> propertyTypeRepository, IRepository<AhlanFeekum.PropertyFeatures.PropertyFeature, Guid> propertyFeatureRepository)
            : base(sitePropertyRepository, sitePropertyManager, downloadTokenCache, propertyTypeRepository, propertyFeatureRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}