using AhlanFeekum.Shared;
using AhlanFeekum.SiteProperties;
using AhlanFeekum.UserProfiles;
using AhlanFeekum.UserPayments;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekum.Permissions;
using AhlanFeekum.Reservations;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekum.Shared;
using Volo.Abp.Users;

namespace AhlanFeekum.Reservations
{
    public class ReservationsAppService : ReservationsAppServiceBase, IReservationsAppService
    {
        //<suite-custom-code-autogenerated>
        public ICurrentUser _currentUser { get; set; }
        private readonly IUserPaymentRepository _userPaymentRepository;
        private readonly IUserProfilesAppService _userProfilesAppService;
        private readonly ILogger<ReservationsAppService> _logger;

        public ReservationsAppService(
            IReservationRepository reservationRepository, 
            ReservationManager reservationManager, 
            IDistributedCache<ReservationDownloadTokenCacheItem, string> downloadTokenCache, 
            IRepository<AhlanFeekum.UserProfiles.UserProfile, Guid> userProfileRepository, 
            IRepository<AhlanFeekum.SiteProperties.SiteProperty, Guid> sitePropertyRepository, 
            ICurrentUser currentUser,
            IUserPaymentRepository userPaymentRepository,
            IUserProfilesAppService userProfilesAppService,
            ILogger<ReservationsAppService> logger)
            : base(reservationRepository, reservationManager, downloadTokenCache, userProfileRepository, sitePropertyRepository)
        {
            _currentUser = currentUser;
            _userPaymentRepository = userPaymentRepository;
            _userProfilesAppService = userProfilesAppService;
            _logger = logger;
        }
        //</suite-custom-code-autogenerated>

        [Authorize(AhlanFeekumPermissions.Reservations.Create)]
        [RemoteService(false)]
        public virtual async Task<ReservationMobileDto> CreateAsync(ReservationCreateMobileDto input)
        {

            if (_currentUser == null || !_currentUser.Id.HasValue)
            {
                throw new UserFriendlyException(L["The {0} field is required.", L["UserProfile"]]);
            }
            if (input.SitePropertyId == default)
            {
                throw new UserFriendlyException(L["The {0} field is required.", L["SiteProperty"]]);
            }

            var status = ((ReservationStatus[])Enum.GetValues(typeof(ReservationStatus)))[0];

            var siteProperty = await _sitePropertyRepository.FirstOrDefaultAsync(s=>s.Id== input.SitePropertyId);
            if (siteProperty == null)
            {
                throw new UserFriendlyException(L["TheSitePropertyNotFound"]);
            }
            var reservation = await _reservationManager.CreateAsync(
            _currentUser.Id.Value, input.SitePropertyId, input.FromeDate, input.ToDate, siteProperty.PricePerNight, status, null, null, input.NumberOfGuest, 0, input.Notes
            );

            return ObjectMapper.Map<ReservationWithNavigationProperties, ReservationMobileDto>(await _reservationRepository.GetWithNavigationPropertiesAsync(reservation.Id));
        }

        [Authorize(AhlanFeekumPermissions.Reservations.Default)]
        public virtual async Task<List<ReservationMobileDto>> UserReservationsAsync(Guid? userId=null)
        {
            Guid? userProfileId = null;
            if (userId != null && userId.HasValue)
                userProfileId = userId.Value;
            else
            {
                if (_currentUser != null)
                    userProfileId = _currentUser.Id.Value;
                else
                    throw new UserFriendlyException("NotLoggedIn");
            }
                GetReservationsInput input = new GetReservationsInput()
                {
                    UserProfileId = userProfileId,
                    SkipCount = 0,
                    MaxResultCount = 1000
                };
          //  var totalCount = await _reservationRepository.GetCountAsync(input.FilterText, input.FromeDateMin, input.FromeDateMax, input.ToDateMin, input.ToDateMax, input.CheckInDateMin, input.CheckInDateMax, input.CheckOutDateMin, input.CheckOutDateMax, input.NumberOfGuestMin, input.NumberOfGuestMax, input.PriceMin, input.PriceMax, input.DiscountMin, input.DiscountMax, input.ReservationStatus, input.Notes, input.UserProfileId, input.SitePropertyId);
            var items = await _reservationRepository.GetListWithNavigationPropertiesAsync(input.FilterText, input.FromeDateMin, input.FromeDateMax, input.ToDateMin, input.ToDateMax, input.CheckInDateMin, input.CheckInDateMax, input.CheckOutDateMin, input.CheckOutDateMax, input.NumberOfGuestMin, input.NumberOfGuestMax, input.PriceMin, input.PriceMax, input.DiscountMin, input.DiscountMax, input.ReservationStatus, input.Notes, input.UserProfileId, input.SitePropertyId, input.Sorting, input.MaxResultCount, input.SkipCount);
            return ObjectMapper.Map<List<ReservationWithNavigationProperties>, List<ReservationMobileDto>>(items);
            //return new PagedResultDto<ReservationWithNavigationPropertiesDto>
            //{
            //    TotalCount = totalCount,
            //    Items = 
            //};
        }

        public virtual async Task<List<ReservationMobileDto>> UpcomingReservationsAsync(Guid? userId=null, Guid? sitePropertyId = null)
        {
            Guid? userProfileId = null;
            if (userId != null && userId.HasValue)
                userProfileId = userId.Value;
            else
            {
                if (_currentUser != null)
                    userProfileId = _currentUser.Id.Value;
                else
                    throw new UserFriendlyException("NotLoggedIn");
            }
            GetReservationsInput input = new GetReservationsInput()
            {
                UserProfileId = userProfileId,
                SitePropertyId = sitePropertyId,
                FromeDateMin =DateOnly.FromDateTime(DateTime.Now),
                SkipCount = 0,
                MaxResultCount = 1000
            };
            //  var totalCount = await _reservationRepository.GetCountAsync(input.FilterText, input.FromeDateMin, input.FromeDateMax, input.ToDateMin, input.ToDateMax, input.CheckInDateMin, input.CheckInDateMax, input.CheckOutDateMin, input.CheckOutDateMax, input.NumberOfGuestMin, input.NumberOfGuestMax, input.PriceMin, input.PriceMax, input.DiscountMin, input.DiscountMax, input.ReservationStatus, input.Notes, input.UserProfileId, input.SitePropertyId);
            var items = await _reservationRepository.GetListWithNavigationPropertiesAsync(input.FilterText, input.FromeDateMin, input.FromeDateMax, input.ToDateMin, input.ToDateMax, input.CheckInDateMin, input.CheckInDateMax, input.CheckOutDateMin, input.CheckOutDateMax, input.NumberOfGuestMin, input.NumberOfGuestMax, input.PriceMin, input.PriceMax, input.DiscountMin, input.DiscountMax, input.ReservationStatus, input.Notes, input.UserProfileId, input.SitePropertyId, input.Sorting, input.MaxResultCount, input.SkipCount);
            return ObjectMapper.Map<List<ReservationWithNavigationProperties>, List<ReservationMobileDto>>(items);
            //return new PagedResultDto<ReservationWithNavigationPropertiesDto>
            //{
            //    TotalCount = totalCount,
            //    Items = 
            //};
        }

        /// <summary>
        /// Override UpdateAsync to handle payment capture/cancel based on reservation status
        /// </summary>
        [Authorize(AhlanFeekumPermissions.Reservations.Edit)]
        public override async Task<ReservationDto> UpdateAsync(Guid id, ReservationUpdateDto input)
        {
            // Get the current reservation to check if status changed
            var currentReservation = await _reservationRepository.GetAsync(id);
            var oldStatus = currentReservation.ReservationStatus;
            var newStatus = input.ReservationStatus;

            // Update the reservation
            var updatedReservation = await base.UpdateAsync(id, input);

            // Handle payment if status changed
            if (oldStatus != newStatus)
            {
                await HandlePaymentStatusChangeAsync(id, newStatus);
            }

            return updatedReservation;
        }

        /// <summary>
        /// Handles payment capture or cancel based on reservation status
        /// </summary>
        private async Task HandlePaymentStatusChangeAsync(Guid reservationId, ReservationStatus newStatus)
        {
            try
            {
                // Find payment for this reservation with requires_capture status
                var queryable = await _userPaymentRepository.GetQueryableAsync();
                var payment = await AsyncExecuter.FirstOrDefaultAsync(
                    queryable.Where(p => p.ReservationId == reservationId && 
                                        p.Status == UserPaymentStatus.requires_capture)
                );

                if (payment == null)
                {
                    _logger.LogInformation("No payment with requires_capture status found for reservation {ReservationId}", reservationId);
                    return;
                }

                // Capture payment if approved
                if (newStatus == ReservationStatus.Approved)
                {
                    _logger.LogInformation("Reservation {ReservationId} approved - capturing payment {PaymentId}", 
                        reservationId, payment.StripPaymentId);
                    
                    await _userProfilesAppService.CapturePaymentAsync(payment.StripPaymentId);
                    
                    _logger.LogInformation("Payment {PaymentId} captured successfully", payment.StripPaymentId);
                }
                // Cancel payment if rejected or any other non-approved status
                else if (newStatus == ReservationStatus.Rejected || 
                         newStatus == ReservationStatus.Canceled ||
                         newStatus == ReservationStatus.Pending)
                {
                    _logger.LogInformation("Reservation {ReservationId} status changed to {Status} - canceling payment {PaymentId}", 
                        reservationId, newStatus, payment.StripPaymentId);
                    
                    await _userProfilesAppService.CancelPaymentAsync(payment.StripPaymentId);
                    
                    _logger.LogInformation("Payment {PaymentId} canceled successfully", payment.StripPaymentId);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error handling payment for reservation {ReservationId}", reservationId);
                // Don't throw - we don't want to fail the reservation update if payment fails
                // The payment can be handled manually later
            }
        }

        //Write your custom code...
    }
}