using AhlanFeekum.Shared;
using AhlanFeekum.SiteProperties;
using AhlanFeekum.UserProfiles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekum.Permissions;
using AhlanFeekum.Reservations;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekum.Shared;
using Volo.Abp.Users;

namespace AhlanFeekum.Reservations
{
    public class ReservationsAppService : ReservationsAppServiceBase, IReservationsAppService
    {
        //<suite-custom-code-autogenerated>
        public ICurrentUser _currentUser { get; set; }
        public ReservationsAppService(IReservationRepository reservationRepository, ReservationManager reservationManager, IDistributedCache<ReservationDownloadTokenCacheItem, string> downloadTokenCache, IRepository<AhlanFeekum.UserProfiles.UserProfile, Guid> userProfileRepository, IRepository<AhlanFeekum.SiteProperties.SiteProperty, Guid> sitePropertyRepository, ICurrentUser currentUser)
            : base(reservationRepository, reservationManager, downloadTokenCache, userProfileRepository, sitePropertyRepository)
        {
            _currentUser = currentUser;
        }
        //</suite-custom-code-autogenerated>

        [Authorize(AhlanFeekumPermissions.Reservations.Create)]
        [RemoteService(false)]
        public virtual async Task<ReservationMobileDto> CreateAsync(ReservationCreateMobileDto input)
        {

            if (_currentUser == null || !_currentUser.Id.HasValue)
            {
                throw new UserFriendlyException(L["The {0} field is required.", L["UserProfile"]]);
            }
            if (input.SitePropertyId == default)
            {
                throw new UserFriendlyException(L["The {0} field is required.", L["SiteProperty"]]);
            }

            var status = ((ReservationStatus[])Enum.GetValues(typeof(ReservationStatus)))[0];

            var siteProperty = await _sitePropertyRepository.FirstOrDefaultAsync(s=>s.Id== input.SitePropertyId);
            if (siteProperty == null)
            {
                throw new UserFriendlyException(L["TheSitePropertyNotFound"]);
            }
            var reservation = await _reservationManager.CreateAsync(
            _currentUser.Id.Value, input.SitePropertyId, input.FromeDate, input.ToDate, siteProperty.PricePerNight, status, null, null, input.NumberOfGuest, 0, input.Notes
            );

            return ObjectMapper.Map<ReservationWithNavigationProperties, ReservationMobileDto>(await _reservationRepository.GetWithNavigationPropertiesAsync(reservation.Id));
        }

        [Authorize(AhlanFeekumPermissions.Reservations.Default)]
        public virtual async Task<List<ReservationMobileDto>> UserReservationsAsync(Guid? userId)
        {
            GetReservationsInput input = new GetReservationsInput()
            {
                UserProfileId = userId,
                SkipCount = 0,
                MaxResultCount= 1000
            };
            var totalCount = await _reservationRepository.GetCountAsync(input.FilterText, input.FromeDateMin, input.FromeDateMax, input.ToDateMin, input.ToDateMax, input.CheckInDateMin, input.CheckInDateMax, input.CheckOutDateMin, input.CheckOutDateMax, input.NumberOfGuestMin, input.NumberOfGuestMax, input.PriceMin, input.PriceMax, input.DiscountMin, input.DiscountMax, input.ReservationStatus, input.Notes, input.UserProfileId, input.SitePropertyId);
            var items = await _reservationRepository.GetListWithNavigationPropertiesAsync(input.FilterText, input.FromeDateMin, input.FromeDateMax, input.ToDateMin, input.ToDateMax, input.CheckInDateMin, input.CheckInDateMax, input.CheckOutDateMin, input.CheckOutDateMax, input.NumberOfGuestMin, input.NumberOfGuestMax, input.PriceMin, input.PriceMax, input.DiscountMin, input.DiscountMax, input.ReservationStatus, input.Notes, input.UserProfileId, input.SitePropertyId, input.Sorting, input.MaxResultCount, input.SkipCount);
            return ObjectMapper.Map<List<ReservationWithNavigationProperties>, List<ReservationMobileDto>>(items);
            //return new PagedResultDto<ReservationWithNavigationPropertiesDto>
            //{
            //    TotalCount = totalCount,
            //    Items = 
            //};
        }
        //Write your custom code...
    }
}