using AhlanFeekum.Permissions;
using AhlanFeekum.Reservations;
using AhlanFeekum.Shared;
using AhlanFeekum.Shared;
using AhlanFeekum.UserPayments;
using AhlanFeekum.UserProfiles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Caching.Distributed;
using MiniExcelLibs;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Volo.Abp.Content;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekum.UserPayments
{
    public class UserPaymentsAppService : UserPaymentsAppServiceBase, IUserPaymentsAppService
    {
        //<suite-custom-code-autogenerated>
        public UserPaymentsAppService(IUserPaymentRepository userPaymentRepository, UserPaymentManager userPaymentManager, IDistributedCache<UserPaymentDownloadTokenCacheItem, string> downloadTokenCache, IRepository<AhlanFeekum.UserProfiles.UserProfile, Guid> userProfileRepository, IRepository<AhlanFeekum.Reservations.Reservation, Guid> reservationRepository)
            : base(userPaymentRepository, userPaymentManager, downloadTokenCache, userProfileRepository, reservationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
        public virtual async Task<PagedResultDto<LookupDto<int>>> GetPaymentMethodLookupAsync()
        {
            List <LookupDto<int>> lookups = new List<LookupDto<int>>();
            foreach (var itemValue in Enum.GetValues(typeof(PaymentMethod)))
                {
                    lookups.Add(new LookupDto<int>()
                    {
                        Id = (int)itemValue,
                        DisplayName = L[$"Enum:PaymentMethod.{((PaymentMethod)itemValue).ToString("d")}"]
                    });
                };
            return new PagedResultDto<LookupDto<int>>
            {
                TotalCount = lookups.Count,
                Items = lookups
            };
        }
    }
}