using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekum.Permissions;
using AhlanFeekum.PropertyTypes;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekum.Shared;

namespace AhlanFeekum.PropertyTypes
{
    public class PropertyTypesAppService : PropertyTypesAppServiceBase, IPropertyTypesAppService
    {
        //<suite-custom-code-autogenerated>
        public PropertyTypesAppService(IPropertyTypeRepository propertyTypeRepository, PropertyTypeManager propertyTypeManager, IDistributedCache<PropertyTypeDownloadTokenCacheItem, string> downloadTokenCache)
            : base(propertyTypeRepository, propertyTypeManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}