using AhlanFeekum.Shared;
using AhlanFeekum.UserProfiles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekum.Permissions;
using AhlanFeekum.PersonEvaluations;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekum.Shared;

namespace AhlanFeekum.PersonEvaluations
{
    public class PersonEvaluationsAppService : PersonEvaluationsAppServiceBase, IPersonEvaluationsAppService
    {
        //<suite-custom-code-autogenerated>
        public PersonEvaluationsAppService(IPersonEvaluationRepository personEvaluationRepository, PersonEvaluationManager personEvaluationManager, IDistributedCache<PersonEvaluationDownloadTokenCacheItem, string> downloadTokenCache, IRepository<AhlanFeekum.UserProfiles.UserProfile, Guid> userProfileRepository)
            : base(personEvaluationRepository, personEvaluationManager, downloadTokenCache, userProfileRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}