using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekum.Permissions;
using AhlanFeekum.Statuses;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekum.Shared;

namespace AhlanFeekum.Statuses
{
    public class StatusesAppService : StatusesAppServiceBase, IStatusesAppService
    {
        //<suite-custom-code-autogenerated>
        public StatusesAppService(IStatusRepository statusRepository, StatusManager statusManager, IDistributedCache<StatusDownloadTokenCacheItem, string> downloadTokenCache)
            : base(statusRepository, statusManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}