using AhlanFeekum.UserPayments;
using AhlanFeekum.UserPayments;
using AhlanFeekum.UserPayments;
using AhlanFeekum.UserPayments;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekum.UserPayments
{
    public class UserPaymentManager : UserPaymentManagerBase
    {
        //<suite-custom-code-autogenerated>
        public UserPaymentManager(IUserPaymentRepository userPaymentRepository)
            : base(userPaymentRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}