using AhlanFeekum.UserPayments;
using AhlanFeekum.UserProfiles;
using AhlanFeekum.Reservations;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekum.UserPayments
{
    public class UserPayment : UserPaymentBase
    {
        //<suite-custom-code-autogenerated>
        protected UserPayment()
        {

        }

        public UserPayment(Guid id, Guid userProfileId, Guid reservationId, long amount, long amountCapturable, long amountReceived, UserPaymentStatus status, DateTime created, PaymentMethod paymentMethod, string? currency = null, string? description = null, string? receiptEmail = null, string? confirmationMethod = null, string? stripPaymentId = null, string? stripClientSecret = null)
            : base(id, userProfileId, reservationId, amount, amountCapturable, amountReceived, status, created, paymentMethod, currency, description, receiptEmail, confirmationMethod, stripPaymentId, stripClientSecret)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}