using AhlanFeekum.PropertyFeatures;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekum.SiteProperties
{
    public class SitePropertyManager : SitePropertyManagerBase
    {
        //<suite-custom-code-autogenerated>
        public SitePropertyManager(ISitePropertyRepository sitePropertyRepository,
        IRepository<PropertyFeature, Guid> propertyFeatureRepository)
            : base(sitePropertyRepository, propertyFeatureRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}