using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekum.Permissions;
using AhlanFeekum.AhlanfeekumTerms;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekum.Shared;
using Volo.Abp.BlobStoring;

namespace AhlanFeekum.AhlanfeekumTerms
{
    public class AhlanfeekumTermsAppService : AhlanfeekumTermsAppServiceBase, IAhlanfeekumTermsAppService
    {
        //<suite-custom-code-autogenerated>
        public AhlanfeekumTermsAppService(IAhlanfeekumTermRepository ahlanfeekumTermRepository, AhlanfeekumTermManager ahlanfeekumTermManager, IDistributedCache<AhlanfeekumTermDownloadTokenCacheItem, string> downloadTokenCache, IRepository<AppFileDescriptors.AppFileDescriptor, Guid> appFileDescriptorRepository, IBlobContainer<AhlanfeekumTermFileContainer> blobContainer)
            : base(ahlanfeekumTermRepository, ahlanfeekumTermManager, downloadTokenCache, appFileDescriptorRepository, blobContainer)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...

        [AllowAnonymous]
        [RemoteService(false)]
        public virtual async Task<AhlanfeekumTermMobileDto> GetAsync()
        {
            var list = await _ahlanfeekumTermRepository.GetListAsync(isActive: true, sorting: "CreationTime desc", skipCount:0, maxResultCount: 1);
            if(!list.IsNullOrEmpty())
                return ObjectMapper.Map<AhlanfeekumTerm, AhlanfeekumTermMobileDto>(list[0]);
            return null;
        }
    }
}